// Code generated by Arduino IoT Cloud, DO NOT EDIT.

// #include <ArduinoIoTCloud.h>
// #include <Arduino_ConnectionHandler.h>


#include "arduino_secrets_teakport.h"
// #include "arduino_secrets_compass.h"

// const char DEVICE_LOGIN_NAME[] = "22153d4b-5ffc-474d-841e-c4f80f61206d";

const char WIFI_SSID[]               = SECRET_SSID;    // Network SSID (name)
const char WIFI_PASSWORD[] = SECRET_PASS;              // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

const char THINGSBOARD_SERVER[] = "thingsboard.cloud";

int random_value;
bool led_switch;
float humidity;
float tempCel;
float tempFahr;

void initProperties(){



  //   ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  //   ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  //   ArduinoCloud.addProperty(random_value, READ, ON_CHANGE, NULL);
  //   ArduinoCloud.addProperty(led_switch, READWRITE, ON_CHANGE, onLedSwitchChange);
  //   ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  //   ArduinoCloud.addProperty(tempCel, READ, ON_CHANGE, NULL);
  //   ArduinoCloud.addProperty(tempFahr, READ, ON_CHANGE, NULL);
  //   ArduinoCloud.addProperty(random_value, READ, ON_CHANGE, NULL);
}

// WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
